CREATE TABLE METODOSPAGO (
   ID_METODOPAGO         INT                  GENERATED ALWAYS AS IDENTITY,
   MPG_NOMBRE            CHAR(15)             NOT NULL,
   MPG_DIFERIDO          BOOLEAN              NOT NULL,
   MPG_PLAZOS            INT                  NULL,
   MPG_ESTADO            BOOLEAN              NOT NULL,
   MPG_NUMERO_REFERENCIA BOOLEAN              NULL,
   CONSTRAINT PK_METODOSPAGO PRIMARY KEY (ID_METODOPAGO)
);

CREATE TABLE DOCUMENTOXPAGO (
   ID_DOCUMENTO          INT                  NOT NULL,
   ID_METODOPAGO         INT                  NOT NULL,
   DXP_MONTO_ABOONADO    DECIMAL(10,2)        NOT NULL,
   DXP_REFERENCIA        CHAR(13)             NULL,
   DXP_MESESPLAZO        INT                  NULL,
   CONSTRAINT PK_DOCUMENTOXPAGO PRIMARY KEY (ID_DOCUMENTO, ID_METODOPAGO)
);

CREATE TABLE DOCUMENTOS (
   ID_DOCUMENTO          INT                  GENERATED ALWAYS AS IDENTITY,
   ID_CLIENTE            INT                  NOT NULL,
   DOC_ID_DOCUMENTO      INT                  NULL,
   ID_VENDEDOR           INT                  NOT NULL, 
   DOC_TIPO              DOM_DOCUMENTOS       NOT NULL,
   DOC_EMISION           TIMESTAMP            NOT NULL,
   DOC_PAGO              TIMESTAMP            NULL,
   DOC_DESCRIPCION       VARCHAR(50)          NOT NULL,
   DOC_SUBTOTAL          DECIMAL(12,4)        NOT NULL,
   DOC_IVA               DECIMAL(12,4)        NOT NULL,
   DOC_DESCUENTO         DECIMAL(12,4)        NOT NULL,
   DOC_TOTAL             DECIMAL(12,4)        NOT NULL,
   DOC_ESTADO            DOM_ESTADO_DOC       NOT NULL,
   CONSTRAINT PK_DOCUMENTOS PRIMARY KEY (ID_DOCUMENTO)
);

CREATE TABLE VENDEDORES (
   ID_VENDEDOR           INT                  GENERATED ALWAYS AS IDENTITY,
   ID_EMPLEADO           INT                  NOT NULL,
   VEN_COMISION          DECIMAL(2,1)         NOT NULL,
   VEN_META              INT                  NOT NULL,
   VEN_ESTADO            CHAR(3)              NOT NULL,
   CONSTRAINT PK_VENDEDORES PRIMARY KEY (ID_VENDEDOR)
);

CREATE TABLE CUOTAS (
   ID_CUOTA              INT                  GENERATED ALWAYS AS IDENTITY,
   ID_DOCUMENTO          INT                  NULL,
   CUO_NUMERO            INT                  NOT NULL,
   CUO_MONTO             DECIMAL(10,2)        NOT NULL,
   CUO_PENDIENTE         DECIMAL(10,2)        NOT NULL,
   CUO_FECHA_PAGADO      TIMESTAMP            NULL,
   CUO_FECHA_ESTIMADA    TIMESTAMP            NOT NULL,
   CUO_ESTADO            CHAR(3)              NOT NULL,
   CONSTRAINT PK_CUOTAS PRIMARY KEY (ID_CUOTA)
);

CREATE TABLE CLIENTES (
   ID_CLIENTE            INT                  GENERATED ALWAYS AS IDENTITY,
   ID_CIUDAD             INT                  NOT NULL,
   CLI_NOMBRE            VARCHAR(80)          NOT NULL,
   CLI_CIRUC             CHAR(13)             NOT NULL,
   CLI_CELULAR           CHAR(10)             NOT NULL,
   CLI_TELEFONO          CHAR(8)              NOT NULL,
   CLI_CORREO            VARCHAR(100)         NOT NULL,
   CLI_CATEGORIA         DOM_CALIDAD_CLIENTES NOT NULL,
   CLI_ESTADO            BOOLEAN              NOT NULL,
   CONSTRAINT PK_CLIENTES PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE CIUDAD (
   ID_CIUDAD             INT                  GENERATED ALWAYS AS IDENTITY,
   CIU_NOMBRE            CHAR(45)             NOT NULL,
   CIU_ABREVIADO         CHAR(5)              NOT NULL,
   CIU_ESTADO            BOOLEAN              NOT NULL,
   CONSTRAINT PK_CIUDAD PRIMARY KEY (ID_CIUDAD)
);

CREATE TABLE DIRECCIONES (
   ID_DIRECCION          INT                  GENERATED ALWAYS AS IDENTITY,
   ID_CLIENTE            INT                  NOT NULL,
   ID_CIUDAD             INT                  NOT NULL,
   DIR_SECTOR            VARCHAR(25)          NOT NULL,
   DIR_PRINCIPAL         VARCHAR(50)          NOT NULL,
   DIR_SECUNDARIA        VARCHAR(25)          NULL,
   DIR_REFERENCIA        VARCHAR(100)         NOT NULL,
   DIR_ESTADO            BOOLEAN              NOT NULL,
   CONSTRAINT PK_DIRECCIONES PRIMARY KEY (ID_DIRECCION)
);

CREATE TABLE INTERACCIONES (
   ID_INTERACCION        INT                  GENERATED ALWAYS AS IDENTITY,
   ID_CLIENTE            INT                  NOT NULL,
   ID_DOCUMENTO          INT                  NOT NULL,
   INT_TIPO              DOM_INTERACCIONES    NOT NULL,
   INT_CANAL             DOM_CANALES_CONTACTO NOT NULL,
   INT_INCONVENIENTE     VARCHAR(200)         NOT NULL,
   INT_APERTURA          TIMESTAMP            NOT NULL,
   INT_CIERRE            TIMESTAMP            NULL,
   INT_ESTADO            DOM_INTERACCIONES    NOT NULL,
   CONSTRAINT PK_INTERACCIONES PRIMARY KEY (ID_INTERACCION)
);

CREATE TABLE LOGISTICA (
   ID_LOGISTICA          INT                  GENERATED ALWAYS AS IDENTITY,
   ID_DOCUMENTO          INT                  NOT NULL,
   ID_DIRECCION          INT                  NOT NULL,
   LOG_DESPACHO          TIMESTAMP            NOT NULL,
   LOG_ESTIMADA          TIMESTAMP            NOT NULL,
   LOG_REAL              TIMESTAMP            NULL,
   LOG_ESTADO            DOM_ESTADO_LOG       NOT NULL,
   CONSTRAINT PK_LOGISTICA PRIMARY KEY (ID_LOGISTICA)
);

CREATE TABLE PRODUCTOSXLOGISTICA (
   ID_LOGISTICA          INT                  NOT NULL,
   ID_VARIANTE           INT                  NOT NULL,
   PXL_CANTIDAD          INT                  NOT NULL,
   PXL_ESTADO            CHAR(3)              NOT NULL,
   CONSTRAINT PK_PRODUCTOSXLOGISTICA PRIMARY KEY (ID_LOGISTICA, ID_VARIANTE)
);

CREATE TABLE PRODUCTOSXDOCUMENTO (
   ID_DOCUMENTO          INT                  NOT NULL,
   ID_VARIANTE           INT                  NOT NULL,
   PXD_CANTIDAD          INT                  NOT NULL,
   PXD_VALOR_UNITARIO    DECIMAL(10,2)        NOT NULL,
   PXD_VALOR_SUBTOTAL    DECIMAL(10,2)        NOT NULL,
   PXD_ESTADO            DOM_ESTADO_DOC       NOT NULL,
   CONSTRAINT PK_PRODUCTOSXDOCUMENTO PRIMARY KEY (ID_DOCUMENTO, ID_VARIANTE)
);  

ALTER TABLE CLIENTES ADD CONSTRAINT FK_CLIENTES_PERTENECE_CIUDAD FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD (ID_CIUDAD);
ALTER TABLE CUOTAS ADD CONSTRAINT FK_CUOTAS_GENERAN_DOCUMENT FOREIGN KEY (ID_DOCUMENTO) REFERENCES DOCUMENTOS (ID_DOCUMENTO);
ALTER TABLE DOCUMENTOS ADD CONSTRAINT FK_DOCUMENT_CREA2_VENDEDOR FOREIGN KEY (ID_VENDEDOR) REFERENCES VENDEDORES (ID_VENDEDOR);
ALTER TABLE DOCUMENTOS ADD CONSTRAINT FK_DOCUMENT_REFIERE_DOCUMENT FOREIGN KEY (DOC_ID_DOCUMENTO) REFERENCES DOCUMENTOS (ID_DOCUMENTO);
ALTER TABLE DOCUMENTOS ADD CONSTRAINT FK_DOCUMENT_REGISTRA_CLIENTES FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE);
ALTER TABLE DOCUMENTOXPAGO ADD CONSTRAINT FK_DOCUMENT_DOCUMENTO_METODOSP FOREIGN KEY (ID_METODOPAGO) REFERENCES METODOSPAGO (ID_METODOPAGO);
ALTER TABLE DOCUMENTOXPAGO ADD CONSTRAINT FK_DOCUMENT_DOCUMENTO_DOCUMENT FOREIGN KEY (ID_DOCUMENTO) REFERENCES DOCUMENTOS (ID_DOCUMENTO);
ALTER TABLE INTERACCIONES ADD CONSTRAINT FK_INTERACC_REALIZA_CLIENTES FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE);
ALTER TABLE INTERACCIONES ADD CONSTRAINT FK_INTERACC_REFERENCI_DOCUMENT FOREIGN KEY (ID_DOCUMENTO) REFERENCES DOCUMENTOS (ID_DOCUMENTO);
ALTER TABLE LOGISTICA ADD CONSTRAINT FK_LOGISTIC_DESPACHA_DIRECCIO FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCIONES (ID_DIRECCION);
ALTER TABLE LOGISTICA ADD CONSTRAINT FK_LOGISTIC_ENTREGA_DOCUMENT FOREIGN KEY (ID_DOCUMENTO) REFERENCES DOCUMENTOS (ID_DOCUMENTO);
ALTER TABLE PRODUCTOSXDOCUMENTO ADD CONSTRAINT FK_PRODUCTO_PRODUCTOS_DOCUMENT FOREIGN KEY (ID_DOCUMENTO) REFERENCES DOCUMENTOS (ID_DOCUMENTO);
ALTER TABLE PRODUCTOSXLOGISTICA ADD CONSTRAINT FK_PRODUCTO_PRODUCTOS_LOGISTIC FOREIGN KEY (ID_LOGISTICA) REFERENCES LOGISTICA (ID_LOGISTICA);